source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

def new_pods
	pod 'Alamofire', '~> 3.0'
end

def test_pods
	pod 'Quick', '~> 0.8.0'
    pod 'Nimble', '3.0.0'
end

target 'PhunwareTestSwift' do
	new_pods
end

target 'PhunwareTestSwiftTests' do
	test_pods
end

